### ISSUE TITLE
PHP 5.6 and HTTPS

### ISSUE THREAD

**Issue by TeLiXj** [Smart-Core/AcceleratorCacheBundle#14]
If you use this bundle with this combination don't work because SSL streams have been changed in PHP 5.6. You can read more in http://php.net/manual/en/migration56.openssl.php. In the bottom of this page you have the solution: disable verify peer.

``` php
<?php
            $streamContext = stream_context_create([
                'ssl' => [
                    'verify_peer'      => false,
                    'verify_peer_name' => false
                ]
            ]);
            $contents = file_get_contents('https://url', false, $streamContext);
?>
```

If you like I can create a pull request adding this to CacheClearerService, but not just now because I don't have time

**Comment by kbond** [comment]
You can add this to your `config.yml`:

``` yaml
accelerator_cache:
    curl_opts:
        CURLOPT_SSL_VERIFYHOST: false
        CURLOPT_SSL_VERIFYPEER: false
```
